name: build
on: [push]
jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x gradlew
      - run: chmod -R 777 ./
      - name: Build Library
        run: ./gradlew autobindings:build
      - name: Build Compiler
        run: ./gradlew autobindings-compiler:build
