name: Build and Release
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Creating local properties file
        run: echo signing.keyId=${{ secrets.SIGNING_KEYID }} >> local.properties
      - run: echo signing.password=${{ secrets.SIGNING_PASSWORD }} >> local.properties
      - run: echo ossrhUsername=${{ secrets.OSSRH_USERNAME }} >> local.properties 
      - run: echo ossrhPassword=${{ secrets.OSSRH_PASSWORD }} >> local.properties      
      - name: Creating key.gpg
        id: write_file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'key.gpg'
          encodedString: ${{ secrets.SIGNING_KEY_GPG }}
      - run: echo ${{ steps.write_file.outputs.filePath }}
      - run: echo signing.secretKeyRingFile=D\:\\a\\_temp\\key.gpg >> local.properties      
      - run: type local.properties  
      - run: chmod +x gradlew
      - name: Stage annotations
        run: ./gradlew binding-annotations:uploadArchives
      - name: Stage compiler
        run: ./gradlew binding-processor:uploadArchives
      - name: Stage library
        run: ./gradlew app:library:publishReleasePublicationToSonatypeRepository
      - name: Closing repository
        run: ./gradlew closeRepository
      - name: Release repository
        run: ./gradlew releaseRepository